name: Tests
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
jobs:
  symfony-3:
    name: php 7.1
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master
      - uses: docker://php:7.1-cli
      - name: phpunit
        run: |
          php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
          php composer-setup.php
          php -r "unlink('composer-setup.php');"
          php composer.phar require symfony/framework-bundle:^3.4 --no-update
          php composer.phar install
          vendor/bin/simple-phpunit
  symfony-4:
    name: php 7.2
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master
      - uses: docker://php:7.2-cli
      - name: phpunit
        run: |
          php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
          php composer-setup.php
          php -r "unlink('composer-setup.php');"
          php composer.phar require symfony/framework-bundle:^4.3 --no-update
          php composer.phar install
          vendor/bin/simple-phpunit
  symfony-5:
    name: php 7.3
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master
      - uses: docker://php:7.3-cli
      - name: phpunit
        run: |
          php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
          php composer-setup.php
          php -r "unlink('composer-setup.php');"
          php composer.phar install
          vendor/bin/simple-phpunit